Repository jenkins-x/terraform-aws-eks-jx, pull requests merged in 2020-07, with the labels that each got.

#90 feat: using on-demand as default billing for dynamodb
  modules/vault/main.tf
  modules/vault/variables.tf
Labels: approved, lgtm, ok-to-test, size/S

#89 feat: using private subnets as default and adding an option to use public subnets
  README.md
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/M

#106 fix: allow enduser to specify node group disk size
  Makefile
  examples/backend/outputs.tf
  examples/basic/outputs.tf
  examples/nodegroup/outputs.tf
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  modules/vault/main.tf
  modules/vault/outputs.tf
Labels: approved, lgtm, size/M

#104 feat: expose eks module's aws_auth mappers
  README.md
  examples/dev-team/main.tf
  examples/dev-team/outputs.tf
  examples/dev-team/user-alice.tf
  examples/dev-team/user-bob.tf
  examples/dev-team/user-group-developers.tf
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/L

#117 chore: change aws creds mount path
  examples/dev-team/main.tf
  examples/dev-team/outputs.tf
  jenkins-x.yml
  modules/cluster/main.tf
  modules/cluster/variables.tf
Labels: approved, lgtm, size/M

#119 fix: add recursive flag to terraform fmt
  Makefile
  examples/backend/main.tf
  examples/basic/main.tf
  modules/cluster/irsa.tf
  modules/cluster/outputs.tf
  modules/dns/outputs.tf
  modules/dns/variables.tf
  modules/vault/local.tf
Labels: approved, lgtm, size/L

#102 docs: README updates
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#111 chore: Add Ankit to the owners file
  OWNERS
Labels: ok-to-test, size/S

#109 feat(backup): velero storage and IAM
  README.md
  main.tf
  modules/backup/main.tf
  modules/backup/output.tf
  modules/backup/variables.tf
  modules/jx-requirements.yml.tpl
  outputs.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/L

#112 feat: nat gateway
  README.md
  examples/nat/main.tf
  examples/nat/outputs.tf
  examples/nat/variables.tf
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/M
