Repository jenkins-x/terraform-aws-eks-jx, pull requests merged in 2020-08, with the labels that each got.

#87 feat: add an option to be able to specify ssh key pair name, ebs volume size and type to the auto launch configuration
  README.md
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/M

#121 feat: support for terraform 0.13
  main.tf
  modules/cluster/irsa.tf
  modules/cluster/local.tf
  modules/cluster/main.tf
  versions.tf
Labels: approved, lgtm, size/M

#127 fix: make key_name optional
  README.md
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, size/S

#133 refactor: remove jx ui service account creation
  modules/cluster/irsa.tf
  modules/cluster/outputs.tf
  outputs.tf
  spec/test_spec.sh
Labels: approved, lgtm, size/M

#136 docs: Add aws-cli as prerequisite
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#139 feat: disable namespace creation when creating resources for jx3
  README.md
  local.tf
  main.tf
  modules/backup/main.tf
  modules/backup/variables.tf
  modules/cluster/irsa.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  modules/dns/variables.tf
  modules/vault/variables.tf
  outputs.tf
  templates/jx-requirements.yml.tpl
  variables.tf
Labels: approved, lgtm, size/L

#143 fix: empty tuple when setting jx2 boolean variable to false
  modules/cluster/irsa.tf
Labels: approved, lgtm, size/S

#146 fix: set ignoreLoadBalancer to false by default
  README.md
  local.tf
  templates/jx-requirements.yml.tpl
  variables.tf
Labels: approved, lgtm, size/S

#148 fix: check for existence of namespace to avoid error after a destroy
  modules/cluster/irsa.tf
Labels: approved, lgtm, size/M

#151 feat: expose cluster oidc issuer url - fixes #150
  README.md
  outputs.tf
Labels: approved, lgtm, ok-to-test, size/XS

#149 feat: add a secret to store service account annotations
  modules/cluster/main.tf
Labels: approved, lgtm, size/S

#130 feat: cluster autoscaler - fixes #135
  README.md
  modules/cluster/irsa.tf
  modules/cluster/outputs.tf
  outputs.tf
Labels: approved, lgtm, ok-to-test, size/L

#154 fix: fix name for the controllerbuild service account
  modules/cluster/main.tf
Labels: approved, lgtm, size/XS

#156 feat: expose cluster access variables
  README.md
  examples/cluster-access/main.tf
  examples/cluster-access/outputs.tf
  examples/cluster-access/variables.tf
  examples/jx3/main.tf
  examples/jx3/outputs.tf
  examples/jx3/variables.tf
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, size/L
