Repository jenkins-x/terraform-aws-eks-jx, pull requests merged in 2020-12, with the labels that each got.

#217 feat: add flags to control domain management
  README.md
  main.tf
  modules/dns/main.tf
  modules/dns/outputs.tf
  modules/dns/variables.tf
  outputs.tf
  variables.tf
Labels: approved, lgtm, size/M

#219 feat: support tf 0.14
  versions.tf
Labels: approved, lgtm, size/XS

#221 feat: create iam role for pipeline visualizer
  README.md
  examples/jx3/outputs.tf
  modules/cluster/irsa.tf
  modules/cluster/local.tf
  modules/cluster/outputs.tf
  modules/cluster/variables.tf
  outputs.tf
  test/terraform_eks_test.go
  variables.tf
Labels: approved, lgtm, size/M

#224 fix: update vpc and irsa module to support tf 0.14
  modules/cluster/irsa.tf
  modules/cluster/main.tf
Labels: approved, lgtm, size/S

#225 fix: add object access to visualizer policy
  modules/cluster/irsa.tf
Labels: approved, lgtm, ok-to-test, size/XS

#227 fix: move versions from provider blocks
  .gitignore
  Makefile
  examples/existing-cluster/main.tf
  modules/cluster/main.tf
  modules/health/main.tf
  modules/vault/local.tf
  modules/vault/main.tf
  versions.tf
Labels: approved, lgtm, size/M
