Repository jenkins-x/terraform-aws-eks-jx, pull requests merged in 2020-06, with the labels that each got.

#64 docs: fix location in README to add IAM Roles for Service Accounts
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#69 fix: check for empty tuple when accessing s3 bucket information
  main.tf
Labels: approved, lgtm, size/XS

#76 feat: adding an option to use spot instances
  README.md
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/M

#82 chore: update external module versions
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  modules/dns/main.tf
  modules/vault/main.tf
  modules/vault/variables.tf
Labels: approved, lgtm, size/L

#93 docs: fix broken link in readme for configuring vault for eks
  README.md
Labels: approved, lgtm, size/XS

#80 feat: add support for eks managed node group
  README.md
  examples/nodegroup/main.tf
  examples/nodegroup/variables.tf
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, size/L

#98 feat: removing the local file output for jx-requirements.yml
  README.md
  examples/backend/outputs.tf
  examples/basic/outputs.tf
  examples/nodegroup/outputs.tf
  images/terraform-aws-eks-jx.png
  main.tf
  outputs.tf
  variables.tf
Labels: approved, lgtm, size/L
