Repository jenkins-x/terraform-aws-eks-jx, pull requests merged in 2020-11, with the labels that each got.

#190 fix: fixed deprecate
  modules/cluster/local.tf
Labels: approved, lgtm, ok-to-test, size/XS

#193 fix: do not provision worker group launch templates for eks managed node group
  modules/cluster/main.tf
Labels: approved, lgtm, size/XS

#194 feat: expose variables to control cluster and vpc creation
  README.md
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, size/M

#195 feat: disable vault resource creation if vault is not used
  README.md
  examples/asm/main.tf
  examples/asm/outputs.tf
  examples/asm/variables.tf
  local.tf
  main.tf
  modules/vault/local.tf
  modules/vault/main.tf
  modules/vault/variables.tf
  templates/jx-requirements.yml.tpl
  variables.tf
Labels: approved, lgtm, size/L

#197 fix: pass region to eks update-config
  README.md
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
Labels: approved, lgtm, size/S

#199 feat: install kuberhealthy components
  examples/jx3/main.tf
  jenkins-x.yml
  main.tf
  modules/health/main.tf
  modules/health/variables.tf
  variables.tf
Labels: approved, lgtm, size/M

#201 feat: add option to encrypt ebs volumes for self managed worker nodes
  README.md
  examples/asm/main.tf
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, size/M

#203 fix: use set_sensitive instead of set for bot token
  modules/cluster/charts.tf
Labels: approved, lgtm, size/XS

#205 feat: add envelope encryption for k8s secrets
  README.md
  examples/envelope-encryption/main.tf
  examples/envelope-encryption/outputs.tf
  examples/envelope-encryption/variables.tf
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, size/L

#210 feat: custom velero username
  README.md
  main.tf
  modules/backup/main.tf
  modules/backup/variables.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/S

#212 feat: add flags to control iam role creation for existing clusters
  README.md
  modules/backup/main.tf
  modules/backup/variables.tf
  modules/cluster/irsa.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, size/L

#215 fix: use data source to find oidc url for existing clusters
  modules/cluster/irsa.tf
  modules/cluster/local.tf
Labels: approved, lgtm, size/XS
