Repository jenkins-x/terraform-aws-eks-jx, pull requests merged in 2020-05, with the labels that each got.

#35 fix: adding note to README about use of jx-requirements.yml
  README.md
Labels: approved, size/XS

#41 chore: Switch to Lighthouse as default webhook provider
  jx-requirements.yml.tpl
Labels: approved, lgtm, size/XS

#44 fix: expose cluster version variable
  README.md
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, size/S

#45 fix: use data source to attach vault policy
  modules/vault/main.tf
Labels: approved, lgtm, ok-to-test, size/XS

#48 fix: bump up terraform min required version to 0.12.17 to support trim* functions
  .gitignore
  CONTRIBUTING.md
  README.md
  local.tf
  main.tf
Labels: approved, lgtm, ok-to-test, size/S

#60 fix: add explicit dependence on resource creation when querying data source
  modules/vault/main.tf
Labels: approved, lgtm, ok-to-test, size/XS

#59 fix: invalid index error
  main.tf
  modules/cluster/outputs.tf
  modules/vault/outputs.tf
  outputs.tf
Labels: approved, lgtm, ok-to-test, size/S

#61 fix: delete non-empty s3 buckets created by the module
  README.md
  main.tf
  modules/cluster/storage.tf
  modules/cluster/variables.tf
  modules/vault/main.tf
  modules/vault/variables.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/M

#55 docs: add wget to the list of pre-reqs
  README.md
Labels: approved, lgtm, ok-to-test, size/XS
