Repository jenkins-x/terraform-aws-eks-jx, pull requests merged in 2020-09, with the labels that each got.

#152 feat: Create Launch Templates for each AZ - fixes #131
  README.md
  examples/worker-group-launch-templates/main.tf
  examples/worker-group-launch-templates/outputs.tf
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/L

#160 fix: add AssumeRoleWithWebIdentity to tekton bot policy
  modules/cluster/irsa.tf
Labels: approved, lgtm, size/XS

#162 fix: create iam role for tekton sa in jx3
  modules/cluster/irsa.tf
Labels: approved, lgtm, size/S

#164 fix: modify tekton sa role name
  modules/cluster/irsa.tf
Labels: approved, lgtm, size/XS

#166 fix: add ECR poweruser policy to nodegroup iam
  modules/cluster/main.tf
Labels: approved, lgtm, size/XS

#168 feat: add registry to requirements configmap
  README.md
  local.tf
  main.tf
  templates/jx-requirements.yml.tpl
  variables.tf
Labels: approved, lgtm, size/S

#171 fix: change root volume size for self managed nodes to 50GB
  README.md
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, size/XS

#172 chore: update k8s version to 1.17
  README.md
  variables.tf
Labels: approved, lgtm, size/XS
