Repository jenkins-x/terraform-aws-eks-jx, pull requests merged in 2021-02, with the labels that each got.

#243 fix: use upstream terraform image
  jenkins-x.yml
  scripts/ci.sh
  scripts/lint.sh
  scripts/security.sh
Labels: approved, size/M

#238 feat: bucketrepo irsa
  README.md
  examples/existing-cluster/main.tf
  modules/cluster/irsa.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  modules/health/main.tf
  modules/vault/local.tf
  modules/vault/main.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/M

#237 fix: pass through the create_<app>_role variables
  main.tf
Labels: ok-to-test, size/S

#239 feat: allow additional policies to be passed to tekton IRSA role
  README.md
  main.tf
  modules/cluster/irsa.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/S

#245 fix: fix issues with helm charts and upgrade versions
  examples/existing-cluster/main.tf
  examples/jx3/main.tf
  examples/jx3/variables.tf
  jenkins-x.yml
  main.tf
  modules/cluster/charts.tf
  modules/cluster/main.tf
  modules/cluster/outputs.tf
  modules/health/main.tf
  modules/vault/local.tf
  modules/vault/main.tf
  test/go.mod
  test/go.sum
  test/terraform_eks_test.go
  versions.tf
Labels: approved, lgtm, size/L

#247 fix: conditionally add role_policy_arns
  modules/cluster/irsa.tf
Labels: approved, lgtm, ok-to-test, size/S
